version: '3'
services:
       db:
              build:
                     context: https://github.com/cpandya231/DynamicFormDesigns.git#main
                     dockerfile: logever/Dockerfile-mysql

              ports:
                     - "3307:3306"
              volumes:
                     - db-data:/var/lib/mysql
              expose:
                     - "3307"
              environment:
                     - MYSQL_ROOT_PASSWORD=logever
                     - MYSQL_DATABASE=logever
                     - MYSQL_USER=logever
                     - MYSQL_PASSWORD=logever
                     - MYSQL_ROOT_HOST=%

              healthcheck:
                     test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
                     timeout: 20s
                     retries: 10
              restart: always

       backendserver:
              build:
                     context: https://github.com/cpandya231/DynamicFormDesigns.git#main
                     dockerfile: logever/Dockerfile
              volumes:
                     - backend-data:/app
              ports:
                     - "8080:8080"
              expose:
                     - "8080"
              links:
                     - "db"
              depends_on:
                     - "db"
              restart: always

       frontend:
              build:
                     context: https://github.com/cpandya231/DynamicFormDesigns-FrontEnd.git#main

              volumes:
                     - frontend-data:/app
              links:
                     - "backendserver"
              depends_on:
                     - "backendserver"
              expose:
                     - "4200"
              ports:
                     - "4200:4200"
                     - '49153:49153'

              command: bash -c "npm start"
              restart: always

volumes:
       db-data:
       backend-data:
       frontend-data:
