version: '3'
services:
  db:
    image: 'mysql/mysql-server:5.7'
    ports:
           - "3307:3306"
    expose:
          - "3307"       
    environment:
           - MYSQL_ROOT_PASSWORD=logever
           - MYSQL_DATABASE=logever
           - MYSQL_USER=logever
           - MYSQL_PASSWORD=logever
           - MYSQL_ROOT_HOST=%
    volumes:
           - ./my-datavolume:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
    
  adminer:
    image: adminer
    restart: always
    ports:
           - "9000:8081"

  backendserver:
    build: ./logever/
    ports:
           - "8080:8080"   
    expose:
           - "8080"        
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
    
  frontend:
    build: ../dynamic_form_designs_frontend/
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "4200:4200"     

